name: Build and Release Tauri App

on:
  release:
      types:
        - published 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tauri CLI
        run: yarn global add @tauri-apps/cli

      - name: Install dependencies
        run: yarn install
      
      - name: Build Tauri app
        env: 
          TAURI_SIGNING_PRIVATE_KEY: ${{secrets.TAURI_SIGNING_PRIVATE_KEY}}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD}}
        run: yarn tauri build

      - name: Generate latest.json
        run: |
          echo '{
            "version": "${GITHUB_REF##*/}",
            "signature":"https://github.com/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF##*/}/${GITHUB_REPOSITORY##*/}_${GITHUB_REF##*/}_x64_en-US.msi.sig"
            }",
            "download": {
              "msi": "https://github.com/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF##*/}/${GITHUB_REPOSITORY##*/}_${GITHUB_REF##*/}_x64_en-US.msi",
              "sig": "https://github.com/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF##*/}/${GITHUB_REPOSITORY##*/}_${GITHUB_REF##*/}_x64_en-US.msi.sig"
            }
          }' > latest.json

      - name: Upload MSI to Release
        env:
            GITHUB_TOKEN: ${{ secrets.NERO_SECRET }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/msi/${GITHUB_REPOSITORY##*/}_${GITHUB_REF##*/}_x64_en-US.msi
          asset_name: ${GITHUB_REPOSITORY##*/}_${GITHUB_REF##*/}_x64_en-US.msi
          asset_content_type: application/x-msi

      - name: Upload sig File to Release
        env:
            GITHUB_TOKEN: ${{ secrets.NERO_SECRET }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/msi/${GITHUB_REPOSITORY##*/}_${GITHUB_REF##*/}_x64_en-US.msi.sig
          asset_name: ${GITHUB_REPOSITORY##*/}_${GITHUB_REF##*/}_x64_en-US.msi.sig
          asset_content_type: application/pgp-signature

      - name: Upload latest.json to Release
        env:
            GITHUB_TOKEN: ${{ secrets.NERO_SECRET }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: latest.json
          asset_name: latest.json
          asset_content_type: application/json